"""OpenAI-compatible mock upstream FastAPI app.

Serves deterministic, shape-valid stand-ins for the three hosted endpoints the
Learning Hub calls (wayfinder ticket #265, CONTEXT.md "Mock Upstream"):

- ``POST /v1/embeddings`` — deterministic unit-norm 1536-dim vectors
  (ADR-0014). Same input yields the same vector; distinct inputs yield
  distinct vectors, so pgvector cosine distance is never NaN.
- ``POST /v1/chat/completions`` — a deterministic canned answer, or a valid
  ``interactive_animation`` scene graph when the conversation is the Depth
  Dive generation turn (detected by the scene-graph contract marker in the
  messages), so ``/query`` and ``/dive`` both return realistic responses.
- ``POST /v1/responses`` — a completed ``web_search_call`` with a
  ``url_citation`` annotation carrying a cited URL, matching the shape the
  Depth Dive web-search client parses.

Every endpoint sleeps a configurable simulated latency (``MockUpstreamSettings``),
disabled for pure-throughput sweeps.
"""

import asyncio
import hashlib
import json
import math
import random

from fastapi import APIRouter, FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict, Field

from mock_upstream.settings import settings

_MOCKED_ANSWER = "Mocked answer generated by the mock upstream for load runs."
"""Deterministic chat-completions content returned for ordinary conversations."""

_EMBEDDING_DIMENSION = 1536
"""Dimensionality of the generated embedding vectors (ADR-0014).

Fixed rather than configurable: the corpus is embedded at 1536 dims, and a
mock returning any other dimension would make pgvector cosine queries fail.
"""

_GENERATION_PROMPT_MARKER = "interactive_animation"
"""Substring that identifies the Depth Dive generation turn.

The generation agent's system prompt (``depth_dive.generation.generation_agent``
describes the ``interactive_animation`` output contract; when the conversation
mentions it, the mock returns a valid scene graph instead of a plain answer so
``/dive`` exercises the full generation-and-parse path. This literal is the
load-run proxy for "this is the generation turn"; it must stay in sync with
that system prompt.
"""

_MOCKED_CITATION_URL = "https://example.com/mock-upstream"
"""Cited URL carried by every mocked web-search result."""

_CANNED_SCENE_GRAPH: dict[str, object] = {
    "output_type": "interactive_animation",
    "title": "Mocked animation",
    "concept": "mocked concept",
    "viewport": {"width": 800, "height": 520},
    "elements": [
        {
            "id": "mocked-element",
            "type": "text",
            "x": 0.0,
            "y": 0.0,
            "text": "Mocked element",
        }
    ],
    "steps": [
        {
            "id": "mocked-step",
            "label": "Mocked step",
            "duration_ms": 1000,
            "element_states": {"mocked-element": {"opacity": 1}},
        }
    ],
    "initial_state": {"mocked-element": {"opacity": 0}},
}
"""A valid ``interactive_animation`` scene graph for the mocked generation turn.

Parses cleanly through the app's ``InteractiveAnimation`` model and passes its
referential-integrity checks (every step reference declared, every element
seeded in ``initial_state``).
"""

router = APIRouter(prefix="/v1")


class EmbeddingsRequest(BaseModel):
    """Request body for ``POST /v1/embeddings`` (OpenAI-compatible)."""

    model_config = ConfigDict(extra="ignore")

    model: str
    input: str | list[str]


class ChatMessage(BaseModel):
    """One chat-completions message (OpenAI-compatible)."""

    model_config = ConfigDict(extra="ignore")

    role: str
    content: str | list[dict[str, object]] = ""


class ChatCompletionRequest(BaseModel):
    """Request body for ``POST /v1/chat/completions`` (OpenAI-compatible)."""

    model_config = ConfigDict(extra="ignore")

    model: str
    messages: list[ChatMessage] = Field(default_factory=list)


class ResponsesRequest(BaseModel):
    """Request body for ``POST /v1/responses`` (OpenAI-compatible)."""

    model_config = ConfigDict(extra="ignore")

    model: str
    input: str = ""
    tools: list[dict[str, object]] | None = None


@router.post("/embeddings", response_model=None)
async def embeddings(request: EmbeddingsRequest) -> dict[str, object] | JSONResponse:
    """Return deterministic embedding vectors for the given input(s).

    Args:
        request: The OpenAI-compatible embeddings request.

    Returns:
        An OpenAI-compatible ``CreateEmbeddingResponse``-shaped payload with
        one deterministic, unit-norm vector per input.
    """
    await _simulate_latency(settings.embeddings_latency_min_ms, settings.embeddings_latency_max_ms)
    failed = _maybe_fail()
    if failed is not None:
        return failed
    inputs = _input_list(request.input)
    data: list[dict[str, object]] = [
        {
            "object": "embedding",
            "index": i,
            "embedding": _embed_vector(text, i, _EMBEDDING_DIMENSION),
        }
        for i, text in enumerate(inputs)
    ]
    prompt_tokens = sum(len(text) for text in inputs)
    return {
        "object": "list",
        "data": data,
        "model": request.model,
        "usage": {"prompt_tokens": prompt_tokens, "total_tokens": prompt_tokens},
    }


@router.post("/chat/completions", response_model=None)
async def chat_completions(request: ChatCompletionRequest) -> dict[str, object] | JSONResponse:
    """Return a deterministic chat-completions response.

    Args:
        request: The OpenAI-compatible chat-completions request.

    Returns:
        An OpenAI-compatible ``ChatCompletion``-shaped payload whose assistant
        content is deterministic — a plain canned answer, or a valid
        ``interactive_animation`` scene graph for the Depth Dive generation
        turn.
    """
    await _simulate_latency(settings.chat_latency_min_ms, settings.chat_latency_max_ms)
    failed = _maybe_fail()
    if failed is not None:
        return failed
    content = _chat_content(request)
    return {
        "id": "chatcmpl_mock_1",
        "object": "chat.completion",
        "created": 1,
        "model": request.model,
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": content},
                "finish_reason": "stop",
            }
        ],
        "usage": {"prompt_tokens": 1, "completion_tokens": 1, "total_tokens": 2},
    }


@router.post("/responses", response_model=None)
async def responses(request: ResponsesRequest) -> dict[str, object] | JSONResponse:
    """Return a completed web-search Responses API payload.

    Args:
        request: The OpenAI-compatible Responses API request.

    Returns:
        An OpenAI-compatible ``Response``-shaped payload: a completed
        ``web_search_call`` plus a message whose ``url_citation`` annotation
        carries a cited URL, matching what the Depth Dive web-search client
        parses into ``WebSearchResult`` items.
    """
    await _simulate_latency(settings.web_search_latency_min_ms, settings.web_search_latency_max_ms)
    failed = _maybe_fail()
    if failed is not None:
        return failed
    text = "The mock upstream stands in for hosted APIs during load runs."
    return {
        "id": "resp_mock_1",
        "created_at": 1,
        "object": "response",
        "model": request.model,
        "status": "completed",
        "parallel_tool_calls": True,
        "tool_choice": "auto",
        "tools": request.tools or [],
        "output": [
            {
                "type": "web_search_call",
                "id": "ws_mock_1",
                "status": "completed",
                "action": {"type": "search", "query": request.input},
            },
            {
                "id": "msg_mock_1",
                "type": "message",
                "status": "completed",
                "role": "assistant",
                "content": [
                    {
                        "type": "output_text",
                        "text": text,
                        "annotations": [
                            {
                                "type": "url_citation",
                                "url": _MOCKED_CITATION_URL,
                                "title": "Mock Upstream Source",
                                "start_index": 0,
                                "end_index": min(len(text), 24),
                            }
                        ],
                    }
                ],
            },
        ],
    }


def create_app() -> FastAPI:
    """Create and configure the mock upstream FastAPI app."""
    app = FastAPI(title="Mock Upstream", version="0.1.0")
    app.include_router(router)
    return app


def _input_list(value: str | list[str]) -> list[str]:
    """Normalize an embeddings ``input`` to a list of strings."""
    if isinstance(value, str):
        return [value]
    return value


def _embed_vector(text: str, index: int, dimension: int) -> list[float]:
    """Build a deterministic, unit-norm vector for one input.

    The vector is seeded by the input's position and content, so identical
    inputs map to identical vectors, distinct inputs map to distinct vectors,
    and every vector has unit norm — never the zero vector, so pgvector
    cosine distance is always defined.
    """
    if dimension <= 0:
        return []
    digest = hashlib.sha256(f"{index}:{text}".encode()).digest()
    rng = random.Random(digest)
    vector = [rng.uniform(-1.0, 1.0) for _ in range(dimension)]
    norm = math.sqrt(sum(value * value for value in vector))
    if norm == 0.0:
        return [1.0] + [0.0] * (dimension - 1)
    return [value / norm for value in vector]


def _chat_content(request: ChatCompletionRequest) -> str:
    """Return the deterministic assistant content for a chat request.

    A conversation mentioning the ``interactive_animation`` contract is the
    Depth Dive generation turn, so the mock returns a canned scene graph that
    parses through the app's ``InteractiveAnimation`` model; every other
    conversation gets a plain canned answer.
    """
    if any(_GENERATION_PROMPT_MARKER in _message_text(message) for message in request.messages):
        return json.dumps(_CANNED_SCENE_GRAPH, separators=(",", ":"))
    return _MOCKED_ANSWER


def _message_text(message: ChatMessage) -> str:
    """Extract the string content of a message, joining text content parts."""
    if isinstance(message.content, str):
        return message.content
    texts: list[str] = []
    for part in message.content:
        text = part.get("text")
        if isinstance(text, str):
            texts.append(text)
    return " ".join(texts)


def _maybe_fail() -> JSONResponse | None:
    """Return a fault-injected error response when the configured roll hits.

    Load runs set ``MOCK_ERROR_RATE``/``MOCK_ERROR_STATUS`` (issue #292) to
    make the mock return e.g. 502/503 responses, so the alert rules that key
    on the api's upstream-error responses can be induced on demand. The roll
    happens after the simulated latency, mimicking a server that processes
    then fails; a zero rate never fails.
    """
    if settings.error_rate <= 0.0:
        return None
    if random.random() >= settings.error_rate:
        return None
    return JSONResponse(
        status_code=settings.error_status,
        content={"detail": f"Mocked upstream failure ({settings.error_status})."},
    )


async def _simulate_latency(min_ms: int, max_ms: int) -> None:
    """Sleep a uniform random delay within ``[min_ms, max_ms]``.

    No sleep when latency is disabled or the range's max is non-positive —
    the pure-throughput mode of the mock (wayfinder ticket #265).
    """
    if not settings.latency_enabled or max_ms <= 0:
        return
    low = min(min_ms, max_ms)
    high = max(min_ms, max_ms)
    await asyncio.sleep(random.uniform(low, high) / 1000.0)


app = create_app()

__all__ = ["app", "create_app"]
